#############################################################################
# Makefile for building: openglwindow
# Generated by qmake (3.0) (Qt 5.7.0)
# Project:  openglwindow.pro
# Template: app
# Command: /home/resod/Qt/5.7/gcc_64/bin/qmake -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile openglwindow.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_QML_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I. -I../../../Qt/5.7/gcc_64/include -I../../../Qt/5.7/gcc_64/include/QtGui -I../../../Qt/5.7/gcc_64/include/QtCore -I. -I../../../Qt/5.7/gcc_64/mkspecs/linux-g++
QMAKE         = /home/resod/Qt/5.7/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = openglwindow1.0.0
DISTDIR = /home/resod/M2/HMIN317/TP_HMIN317/.tmp/openglwindow1.0.0
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/resod/Qt/5.7/gcc_64/lib
LIBS          = $(SUBLIBS) -L/home/resod/Qt/5.7/gcc_64/lib -lQt5Gui -L/usr/lib64 -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = openglwindow.cpp \
		trianglewindow.cpp \
		camera.cpp \
		pool.cpp \
		season.cpp \
		particle.cpp \
		main.cpp moc_openglwindow.cpp \
		moc_trianglewindow.cpp
OBJECTS       = openglwindow.o \
		trianglewindow.o \
		camera.o \
		pool.o \
		season.o \
		particle.o \
		main.o \
		moc_openglwindow.o \
		moc_trianglewindow.o
DIST          = ../../../Qt/5.7/gcc_64/mkspecs/features/spec_pre.prf \
		../../../Qt/5.7/gcc_64/mkspecs/common/unix.conf \
		../../../Qt/5.7/gcc_64/mkspecs/common/linux.conf \
		../../../Qt/5.7/gcc_64/mkspecs/common/sanitize.conf \
		../../../Qt/5.7/gcc_64/mkspecs/common/gcc-base.conf \
		../../../Qt/5.7/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../../Qt/5.7/gcc_64/mkspecs/common/g++-base.conf \
		../../../Qt/5.7/gcc_64/mkspecs/common/g++-unix.conf \
		../../../Qt/5.7/gcc_64/mkspecs/qconfig.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/features/qt_functions.prf \
		../../../Qt/5.7/gcc_64/mkspecs/features/qt_config.prf \
		../../../Qt/5.7/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../../Qt/5.7/gcc_64/mkspecs/features/spec_post.prf \
		../../../Qt/5.7/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt/5.7/gcc_64/mkspecs/features/default_pre.prf \
		openglwindow.pri \
		../../../Qt/5.7/gcc_64/mkspecs/features/resolve_config.prf \
		../../../Qt/5.7/gcc_64/mkspecs/features/default_post.prf \
		../../../Qt/5.7/gcc_64/mkspecs/features/qml_debug.prf \
		../../../Qt/5.7/gcc_64/mkspecs/features/warn_on.prf \
		../../../Qt/5.7/gcc_64/mkspecs/features/qt.prf \
		../../../Qt/5.7/gcc_64/mkspecs/features/resources.prf \
		../../../Qt/5.7/gcc_64/mkspecs/features/moc.prf \
		../../../Qt/5.7/gcc_64/mkspecs/features/unix/opengl.prf \
		../../../Qt/5.7/gcc_64/mkspecs/features/unix/thread.prf \
		../../../Qt/5.7/gcc_64/mkspecs/features/file_copies.prf \
		../../../Qt/5.7/gcc_64/mkspecs/features/testcase_targets.prf \
		../../../Qt/5.7/gcc_64/mkspecs/features/exceptions.prf \
		../../../Qt/5.7/gcc_64/mkspecs/features/yacc.prf \
		../../../Qt/5.7/gcc_64/mkspecs/features/lex.prf \
		openglwindow.pro openglwindow.h \
		trianglewindow.h \
		camera.h \
		pool.h \
		season.h \
		particle.h openglwindow.cpp \
		trianglewindow.cpp \
		camera.cpp \
		pool.cpp \
		season.cpp \
		particle.cpp \
		main.cpp
QMAKE_TARGET  = openglwindow
DESTDIR       = 
TARGET        = openglwindow


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: openglwindow.pro ../../../Qt/5.7/gcc_64/mkspecs/linux-g++/qmake.conf ../../../Qt/5.7/gcc_64/mkspecs/features/spec_pre.prf \
		../../../Qt/5.7/gcc_64/mkspecs/common/unix.conf \
		../../../Qt/5.7/gcc_64/mkspecs/common/linux.conf \
		../../../Qt/5.7/gcc_64/mkspecs/common/sanitize.conf \
		../../../Qt/5.7/gcc_64/mkspecs/common/gcc-base.conf \
		../../../Qt/5.7/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../../Qt/5.7/gcc_64/mkspecs/common/g++-base.conf \
		../../../Qt/5.7/gcc_64/mkspecs/common/g++-unix.conf \
		../../../Qt/5.7/gcc_64/mkspecs/qconfig.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt/5.7/gcc_64/mkspecs/features/qt_functions.prf \
		../../../Qt/5.7/gcc_64/mkspecs/features/qt_config.prf \
		../../../Qt/5.7/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../../Qt/5.7/gcc_64/mkspecs/features/spec_post.prf \
		../../../Qt/5.7/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt/5.7/gcc_64/mkspecs/features/default_pre.prf \
		openglwindow.pri \
		../../../Qt/5.7/gcc_64/mkspecs/features/resolve_config.prf \
		../../../Qt/5.7/gcc_64/mkspecs/features/default_post.prf \
		../../../Qt/5.7/gcc_64/mkspecs/features/qml_debug.prf \
		../../../Qt/5.7/gcc_64/mkspecs/features/warn_on.prf \
		../../../Qt/5.7/gcc_64/mkspecs/features/qt.prf \
		../../../Qt/5.7/gcc_64/mkspecs/features/resources.prf \
		../../../Qt/5.7/gcc_64/mkspecs/features/moc.prf \
		../../../Qt/5.7/gcc_64/mkspecs/features/unix/opengl.prf \
		../../../Qt/5.7/gcc_64/mkspecs/features/unix/thread.prf \
		../../../Qt/5.7/gcc_64/mkspecs/features/file_copies.prf \
		../../../Qt/5.7/gcc_64/mkspecs/features/testcase_targets.prf \
		../../../Qt/5.7/gcc_64/mkspecs/features/exceptions.prf \
		../../../Qt/5.7/gcc_64/mkspecs/features/yacc.prf \
		../../../Qt/5.7/gcc_64/mkspecs/features/lex.prf \
		openglwindow.pro \
		../../../Qt/5.7/gcc_64/lib/libQt5Gui.prl \
		../../../Qt/5.7/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile openglwindow.pro
../../../Qt/5.7/gcc_64/mkspecs/features/spec_pre.prf:
../../../Qt/5.7/gcc_64/mkspecs/common/unix.conf:
../../../Qt/5.7/gcc_64/mkspecs/common/linux.conf:
../../../Qt/5.7/gcc_64/mkspecs/common/sanitize.conf:
../../../Qt/5.7/gcc_64/mkspecs/common/gcc-base.conf:
../../../Qt/5.7/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../../Qt/5.7/gcc_64/mkspecs/common/g++-base.conf:
../../../Qt/5.7/gcc_64/mkspecs/common/g++-unix.conf:
../../../Qt/5.7/gcc_64/mkspecs/qconfig.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_core.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_help.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_location.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_network.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_script.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_scxml.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webview.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Qt/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../Qt/5.7/gcc_64/mkspecs/features/qt_functions.prf:
../../../Qt/5.7/gcc_64/mkspecs/features/qt_config.prf:
../../../Qt/5.7/gcc_64/mkspecs/linux-g++/qmake.conf:
../../../Qt/5.7/gcc_64/mkspecs/features/spec_post.prf:
../../../Qt/5.7/gcc_64/mkspecs/features/exclusive_builds.prf:
../../../Qt/5.7/gcc_64/mkspecs/features/default_pre.prf:
openglwindow.pri:
../../../Qt/5.7/gcc_64/mkspecs/features/resolve_config.prf:
../../../Qt/5.7/gcc_64/mkspecs/features/default_post.prf:
../../../Qt/5.7/gcc_64/mkspecs/features/qml_debug.prf:
../../../Qt/5.7/gcc_64/mkspecs/features/warn_on.prf:
../../../Qt/5.7/gcc_64/mkspecs/features/qt.prf:
../../../Qt/5.7/gcc_64/mkspecs/features/resources.prf:
../../../Qt/5.7/gcc_64/mkspecs/features/moc.prf:
../../../Qt/5.7/gcc_64/mkspecs/features/unix/opengl.prf:
../../../Qt/5.7/gcc_64/mkspecs/features/unix/thread.prf:
../../../Qt/5.7/gcc_64/mkspecs/features/file_copies.prf:
../../../Qt/5.7/gcc_64/mkspecs/features/testcase_targets.prf:
../../../Qt/5.7/gcc_64/mkspecs/features/exceptions.prf:
../../../Qt/5.7/gcc_64/mkspecs/features/yacc.prf:
../../../Qt/5.7/gcc_64/mkspecs/features/lex.prf:
openglwindow.pro:
../../../Qt/5.7/gcc_64/lib/libQt5Gui.prl:
../../../Qt/5.7/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile openglwindow.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents openglwindow.h trianglewindow.h camera.h pool.h season.h particle.h $(DISTDIR)/
	$(COPY_FILE) --parents openglwindow.cpp trianglewindow.cpp camera.cpp pool.cpp season.cpp particle.cpp main.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_openglwindow.cpp moc_trianglewindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_openglwindow.cpp moc_trianglewindow.cpp
moc_openglwindow.cpp: ../../../Qt/5.7/gcc_64/include/QtGui/QWindow \
		../../../Qt/5.7/gcc_64/include/QtGui/qwindow.h \
		../../../Qt/5.7/gcc_64/include/QtCore/QObject \
		../../../Qt/5.7/gcc_64/include/QtCore/qobject.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qobjectdefs.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qnamespace.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qglobal.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qconfig.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qfeatures.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qsystemdetection.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qprocessordetection.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qtypeinfo.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qtypetraits.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qisenum.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qsysinfo.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qlogging.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qflags.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qatomic.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qbasicatomic.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qgenericatomic.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qglobalstatic.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qmutex.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qnumeric.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qversiontagging.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qstring.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qchar.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qbytearray.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qrefcount.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qarraydata.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qstringbuilder.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qlist.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qalgorithms.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qiterator.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qhashfunctions.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qpair.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qbytearraylist.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qstringlist.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qregexp.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qstringmatcher.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qcoreevent.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qscopedpointer.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qmetatype.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qvarlengtharray.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qcontainerfwd.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qobject_impl.h \
		../../../Qt/5.7/gcc_64/include/QtCore/QEvent \
		../../../Qt/5.7/gcc_64/include/QtCore/QMargins \
		../../../Qt/5.7/gcc_64/include/QtCore/qmargins.h \
		../../../Qt/5.7/gcc_64/include/QtCore/QRect \
		../../../Qt/5.7/gcc_64/include/QtCore/qrect.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qsize.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qpoint.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qsurface.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qsurfaceformat.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qwindowdefs.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qicon.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qpixmap.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qpaintdevice.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qcolor.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qrgb.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qrgba64.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qsharedpointer.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qshareddata.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qhash.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qimage.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qpixelformat.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qtransform.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qmatrix.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qpolygon.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qvector.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qregion.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qdatastream.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qiodevice.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qline.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qpainterpath.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qcursor.h \
		../../../Qt/5.7/gcc_64/include/QtGui/QOpenGLFunctions \
		../../../Qt/5.7/gcc_64/include/QtGui/qopenglfunctions.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qopengl.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qt_windows.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qopengles2ext.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qopenglext.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qopenglcontext.h \
		../../../Qt/5.7/gcc_64/include/QtCore/QScopedPointer \
		../../../Qt/5.7/gcc_64/include/QtGui/QSurfaceFormat \
		../../../Qt/5.7/gcc_64/include/QtGui/qopenglversionfunctions.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qvariant.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qmap.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qdebug.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qtextstream.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qlocale.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qset.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qcontiguouscache.h \
		../../../Qt/5.7/gcc_64/include/QtGui/QOpenGLFunctions_4_5_Core \
		../../../Qt/5.7/gcc_64/include/QtGui/qopenglfunctions_4_5_core.h \
		../../../Qt/5.7/gcc_64/include/QtGui/QOpenGLVersionFunctions \
		openglwindow.h \
		../../../Qt/5.7/gcc_64/bin/moc
	/home/resod/Qt/5.7/gcc_64/bin/moc $(DEFINES) -I/home/resod/Qt/5.7/gcc_64/mkspecs/linux-g++ -I/home/resod/M2/HMIN317/TP_HMIN317 -I/home/resod/M2/HMIN317/TP_HMIN317 -I/home/resod/Qt/5.7/gcc_64/include -I/home/resod/Qt/5.7/gcc_64/include/QtGui -I/home/resod/Qt/5.7/gcc_64/include/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include openglwindow.h -o moc_openglwindow.cpp

moc_trianglewindow.cpp: camera.h \
		../../../Qt/5.7/gcc_64/include/QtGui/QOpenGLShaderProgram \
		../../../Qt/5.7/gcc_64/include/QtGui/qopenglshaderprogram.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qglobal.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qconfig.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qfeatures.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qsystemdetection.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qprocessordetection.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qtypeinfo.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qtypetraits.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qisenum.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qsysinfo.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qlogging.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qflags.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qatomic.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qbasicatomic.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qgenericatomic.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qglobalstatic.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qmutex.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qnumeric.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qversiontagging.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qopengl.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qt_windows.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qopengles2ext.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qopenglext.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qvector2d.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qpoint.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qnamespace.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qmetatype.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qbytearray.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qrefcount.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qarraydata.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qstring.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qchar.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qstringbuilder.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qvarlengtharray.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qcontainerfwd.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qalgorithms.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qobjectdefs.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qvector3d.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qvector4d.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qmatrix4x4.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qquaternion.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qgenericmatrix.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qdebug.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qhash.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qiterator.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qlist.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qhashfunctions.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qpair.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qbytearraylist.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qstringlist.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qregexp.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qstringmatcher.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qmap.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qtextstream.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qiodevice.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qobject.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qcoreevent.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qscopedpointer.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qobject_impl.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qlocale.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qvariant.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qshareddata.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qvector.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qset.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qcontiguouscache.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qsharedpointer.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qdatastream.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qrect.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qmargins.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qsize.h \
		../../../Qt/5.7/gcc_64/include/QtGui/QKeyEvent \
		../../../Qt/5.7/gcc_64/include/QtGui/qevent.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qwindowdefs.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qregion.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qkeysequence.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qurl.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qurlquery.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qfile.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qfiledevice.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qtouchdevice.h \
		openglwindow.h \
		../../../Qt/5.7/gcc_64/include/QtGui/QWindow \
		../../../Qt/5.7/gcc_64/include/QtGui/qwindow.h \
		../../../Qt/5.7/gcc_64/include/QtCore/QObject \
		../../../Qt/5.7/gcc_64/include/QtCore/QEvent \
		../../../Qt/5.7/gcc_64/include/QtCore/QMargins \
		../../../Qt/5.7/gcc_64/include/QtCore/QRect \
		../../../Qt/5.7/gcc_64/include/QtGui/qsurface.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qsurfaceformat.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qicon.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qpixmap.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qpaintdevice.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qcolor.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qrgb.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qrgba64.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qimage.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qpixelformat.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qtransform.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qmatrix.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qpolygon.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qline.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qpainterpath.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qcursor.h \
		../../../Qt/5.7/gcc_64/include/QtGui/QOpenGLFunctions \
		../../../Qt/5.7/gcc_64/include/QtGui/qopenglfunctions.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qopenglcontext.h \
		../../../Qt/5.7/gcc_64/include/QtCore/QScopedPointer \
		../../../Qt/5.7/gcc_64/include/QtGui/QSurfaceFormat \
		../../../Qt/5.7/gcc_64/include/QtGui/qopenglversionfunctions.h \
		../../../Qt/5.7/gcc_64/include/QtGui/QOpenGLFunctions_4_5_Core \
		../../../Qt/5.7/gcc_64/include/QtGui/qopenglfunctions_4_5_core.h \
		../../../Qt/5.7/gcc_64/include/QtGui/QOpenGLVersionFunctions \
		../../../Qt/5.7/gcc_64/include/QtCore/QTimer \
		../../../Qt/5.7/gcc_64/include/QtCore/qtimer.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qbasictimer.h \
		season.h \
		particle.h \
		pool.h \
		trianglewindow.h \
		../../../Qt/5.7/gcc_64/bin/moc
	/home/resod/Qt/5.7/gcc_64/bin/moc $(DEFINES) -I/home/resod/Qt/5.7/gcc_64/mkspecs/linux-g++ -I/home/resod/M2/HMIN317/TP_HMIN317 -I/home/resod/M2/HMIN317/TP_HMIN317 -I/home/resod/Qt/5.7/gcc_64/include -I/home/resod/Qt/5.7/gcc_64/include/QtGui -I/home/resod/Qt/5.7/gcc_64/include/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include trianglewindow.h -o moc_trianglewindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

openglwindow.o: openglwindow.cpp openglwindow.h \
		../../../Qt/5.7/gcc_64/include/QtGui/QWindow \
		../../../Qt/5.7/gcc_64/include/QtGui/qwindow.h \
		../../../Qt/5.7/gcc_64/include/QtCore/QObject \
		../../../Qt/5.7/gcc_64/include/QtCore/qobject.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qobjectdefs.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qnamespace.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qglobal.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qconfig.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qfeatures.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qsystemdetection.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qprocessordetection.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qtypeinfo.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qtypetraits.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qisenum.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qsysinfo.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qlogging.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qflags.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qatomic.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qbasicatomic.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qgenericatomic.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qglobalstatic.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qmutex.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qnumeric.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qversiontagging.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qstring.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qchar.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qbytearray.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qrefcount.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qarraydata.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qstringbuilder.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qlist.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qalgorithms.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qiterator.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qhashfunctions.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qpair.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qbytearraylist.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qstringlist.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qregexp.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qstringmatcher.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qcoreevent.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qscopedpointer.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qmetatype.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qvarlengtharray.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qcontainerfwd.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qobject_impl.h \
		../../../Qt/5.7/gcc_64/include/QtCore/QEvent \
		../../../Qt/5.7/gcc_64/include/QtCore/QMargins \
		../../../Qt/5.7/gcc_64/include/QtCore/qmargins.h \
		../../../Qt/5.7/gcc_64/include/QtCore/QRect \
		../../../Qt/5.7/gcc_64/include/QtCore/qrect.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qsize.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qpoint.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qsurface.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qsurfaceformat.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qwindowdefs.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qicon.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qpixmap.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qpaintdevice.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qcolor.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qrgb.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qrgba64.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qsharedpointer.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qshareddata.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qhash.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qimage.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qpixelformat.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qtransform.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qmatrix.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qpolygon.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qvector.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qregion.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qdatastream.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qiodevice.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qline.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qpainterpath.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qcursor.h \
		../../../Qt/5.7/gcc_64/include/QtGui/QOpenGLFunctions \
		../../../Qt/5.7/gcc_64/include/QtGui/qopenglfunctions.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qopengl.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qt_windows.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qopengles2ext.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qopenglext.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qopenglcontext.h \
		../../../Qt/5.7/gcc_64/include/QtCore/QScopedPointer \
		../../../Qt/5.7/gcc_64/include/QtGui/QSurfaceFormat \
		../../../Qt/5.7/gcc_64/include/QtGui/qopenglversionfunctions.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qvariant.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qmap.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qdebug.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qtextstream.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qlocale.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qset.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qcontiguouscache.h \
		../../../Qt/5.7/gcc_64/include/QtGui/QOpenGLFunctions_4_5_Core \
		../../../Qt/5.7/gcc_64/include/QtGui/qopenglfunctions_4_5_core.h \
		../../../Qt/5.7/gcc_64/include/QtGui/QOpenGLVersionFunctions \
		../../../Qt/5.7/gcc_64/include/QtCore/QCoreApplication \
		../../../Qt/5.7/gcc_64/include/QtCore/qcoreapplication.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qeventloop.h \
		../../../Qt/5.7/gcc_64/include/QtGui/QOpenGLContext \
		../../../Qt/5.7/gcc_64/include/QtGui/QOpenGLPaintDevice \
		../../../Qt/5.7/gcc_64/include/QtGui/qopenglpaintdevice.h \
		../../../Qt/5.7/gcc_64/include/QtGui/QPainter \
		../../../Qt/5.7/gcc_64/include/QtGui/qpainter.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qtextoption.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qpen.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qbrush.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qfontinfo.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qfont.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qfontmetrics.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o openglwindow.o openglwindow.cpp

trianglewindow.o: trianglewindow.cpp trianglewindow.h \
		camera.h \
		../../../Qt/5.7/gcc_64/include/QtGui/QOpenGLShaderProgram \
		../../../Qt/5.7/gcc_64/include/QtGui/qopenglshaderprogram.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qglobal.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qconfig.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qfeatures.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qsystemdetection.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qprocessordetection.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qtypeinfo.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qtypetraits.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qisenum.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qsysinfo.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qlogging.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qflags.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qatomic.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qbasicatomic.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qgenericatomic.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qglobalstatic.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qmutex.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qnumeric.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qversiontagging.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qopengl.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qt_windows.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qopengles2ext.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qopenglext.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qvector2d.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qpoint.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qnamespace.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qmetatype.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qbytearray.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qrefcount.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qarraydata.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qstring.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qchar.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qstringbuilder.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qvarlengtharray.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qcontainerfwd.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qalgorithms.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qobjectdefs.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qvector3d.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qvector4d.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qmatrix4x4.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qquaternion.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qgenericmatrix.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qdebug.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qhash.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qiterator.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qlist.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qhashfunctions.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qpair.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qbytearraylist.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qstringlist.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qregexp.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qstringmatcher.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qmap.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qtextstream.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qiodevice.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qobject.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qcoreevent.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qscopedpointer.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qobject_impl.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qlocale.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qvariant.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qshareddata.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qvector.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qset.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qcontiguouscache.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qsharedpointer.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qdatastream.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qrect.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qmargins.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qsize.h \
		../../../Qt/5.7/gcc_64/include/QtGui/QKeyEvent \
		../../../Qt/5.7/gcc_64/include/QtGui/qevent.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qwindowdefs.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qregion.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qkeysequence.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qurl.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qurlquery.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qfile.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qfiledevice.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qtouchdevice.h \
		openglwindow.h \
		../../../Qt/5.7/gcc_64/include/QtGui/QWindow \
		../../../Qt/5.7/gcc_64/include/QtGui/qwindow.h \
		../../../Qt/5.7/gcc_64/include/QtCore/QObject \
		../../../Qt/5.7/gcc_64/include/QtCore/QEvent \
		../../../Qt/5.7/gcc_64/include/QtCore/QMargins \
		../../../Qt/5.7/gcc_64/include/QtCore/QRect \
		../../../Qt/5.7/gcc_64/include/QtGui/qsurface.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qsurfaceformat.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qicon.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qpixmap.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qpaintdevice.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qcolor.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qrgb.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qrgba64.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qimage.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qpixelformat.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qtransform.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qmatrix.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qpolygon.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qline.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qpainterpath.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qcursor.h \
		../../../Qt/5.7/gcc_64/include/QtGui/QOpenGLFunctions \
		../../../Qt/5.7/gcc_64/include/QtGui/qopenglfunctions.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qopenglcontext.h \
		../../../Qt/5.7/gcc_64/include/QtCore/QScopedPointer \
		../../../Qt/5.7/gcc_64/include/QtGui/QSurfaceFormat \
		../../../Qt/5.7/gcc_64/include/QtGui/qopenglversionfunctions.h \
		../../../Qt/5.7/gcc_64/include/QtGui/QOpenGLFunctions_4_5_Core \
		../../../Qt/5.7/gcc_64/include/QtGui/qopenglfunctions_4_5_core.h \
		../../../Qt/5.7/gcc_64/include/QtGui/QOpenGLVersionFunctions \
		../../../Qt/5.7/gcc_64/include/QtCore/QTimer \
		../../../Qt/5.7/gcc_64/include/QtCore/qtimer.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qbasictimer.h \
		season.h \
		particle.h \
		pool.h \
		../../../Qt/5.7/gcc_64/include/QtGui/QMatrix4x4 \
		../../../Qt/5.7/gcc_64/include/QtGui/QScreen \
		../../../Qt/5.7/gcc_64/include/QtGui/qscreen.h \
		../../../Qt/5.7/gcc_64/include/QtCore/QList \
		../../../Qt/5.7/gcc_64/include/QtCore/QSize \
		../../../Qt/5.7/gcc_64/include/QtCore/QSizeF \
		../../../Qt/5.7/gcc_64/include/QtGui/QTransform \
		../../../Qt/5.7/gcc_64/include/QtCore/qmath.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o trianglewindow.o trianglewindow.cpp

camera.o: camera.cpp camera.h \
		../../../Qt/5.7/gcc_64/include/QtGui/QOpenGLShaderProgram \
		../../../Qt/5.7/gcc_64/include/QtGui/qopenglshaderprogram.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qglobal.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qconfig.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qfeatures.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qsystemdetection.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qprocessordetection.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qtypeinfo.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qtypetraits.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qisenum.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qsysinfo.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qlogging.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qflags.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qatomic.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qbasicatomic.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qgenericatomic.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qglobalstatic.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qmutex.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qnumeric.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qversiontagging.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qopengl.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qt_windows.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qopengles2ext.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qopenglext.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qvector2d.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qpoint.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qnamespace.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qmetatype.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qbytearray.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qrefcount.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qarraydata.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qstring.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qchar.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qstringbuilder.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qvarlengtharray.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qcontainerfwd.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qalgorithms.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qobjectdefs.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qvector3d.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qvector4d.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qmatrix4x4.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qquaternion.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qgenericmatrix.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qdebug.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qhash.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qiterator.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qlist.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qhashfunctions.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qpair.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qbytearraylist.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qstringlist.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qregexp.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qstringmatcher.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qmap.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qtextstream.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qiodevice.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qobject.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qcoreevent.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qscopedpointer.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qobject_impl.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qlocale.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qvariant.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qshareddata.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qvector.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qset.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qcontiguouscache.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qsharedpointer.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qdatastream.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qrect.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qmargins.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qsize.h \
		../../../Qt/5.7/gcc_64/include/QtGui/QKeyEvent \
		../../../Qt/5.7/gcc_64/include/QtGui/qevent.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qwindowdefs.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qregion.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qkeysequence.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qurl.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qurlquery.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qfile.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qfiledevice.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qtouchdevice.h \
		../../../Qt/5.7/gcc_64/include/QtGui/QMatrix4x4
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o camera.o camera.cpp

pool.o: pool.cpp pool.h \
		trianglewindow.h \
		camera.h \
		../../../Qt/5.7/gcc_64/include/QtGui/QOpenGLShaderProgram \
		../../../Qt/5.7/gcc_64/include/QtGui/qopenglshaderprogram.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qglobal.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qconfig.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qfeatures.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qsystemdetection.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qprocessordetection.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qtypeinfo.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qtypetraits.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qisenum.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qsysinfo.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qlogging.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qflags.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qatomic.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qbasicatomic.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qgenericatomic.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qglobalstatic.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qmutex.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qnumeric.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qversiontagging.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qopengl.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qt_windows.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qopengles2ext.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qopenglext.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qvector2d.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qpoint.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qnamespace.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qmetatype.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qbytearray.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qrefcount.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qarraydata.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qstring.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qchar.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qstringbuilder.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qvarlengtharray.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qcontainerfwd.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qalgorithms.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qobjectdefs.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qvector3d.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qvector4d.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qmatrix4x4.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qquaternion.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qgenericmatrix.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qdebug.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qhash.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qiterator.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qlist.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qhashfunctions.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qpair.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qbytearraylist.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qstringlist.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qregexp.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qstringmatcher.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qmap.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qtextstream.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qiodevice.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qobject.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qcoreevent.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qscopedpointer.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qobject_impl.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qlocale.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qvariant.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qshareddata.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qvector.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qset.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qcontiguouscache.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qsharedpointer.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qdatastream.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qrect.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qmargins.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qsize.h \
		../../../Qt/5.7/gcc_64/include/QtGui/QKeyEvent \
		../../../Qt/5.7/gcc_64/include/QtGui/qevent.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qwindowdefs.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qregion.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qkeysequence.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qurl.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qurlquery.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qfile.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qfiledevice.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qtouchdevice.h \
		openglwindow.h \
		../../../Qt/5.7/gcc_64/include/QtGui/QWindow \
		../../../Qt/5.7/gcc_64/include/QtGui/qwindow.h \
		../../../Qt/5.7/gcc_64/include/QtCore/QObject \
		../../../Qt/5.7/gcc_64/include/QtCore/QEvent \
		../../../Qt/5.7/gcc_64/include/QtCore/QMargins \
		../../../Qt/5.7/gcc_64/include/QtCore/QRect \
		../../../Qt/5.7/gcc_64/include/QtGui/qsurface.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qsurfaceformat.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qicon.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qpixmap.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qpaintdevice.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qcolor.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qrgb.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qrgba64.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qimage.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qpixelformat.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qtransform.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qmatrix.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qpolygon.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qline.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qpainterpath.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qcursor.h \
		../../../Qt/5.7/gcc_64/include/QtGui/QOpenGLFunctions \
		../../../Qt/5.7/gcc_64/include/QtGui/qopenglfunctions.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qopenglcontext.h \
		../../../Qt/5.7/gcc_64/include/QtCore/QScopedPointer \
		../../../Qt/5.7/gcc_64/include/QtGui/QSurfaceFormat \
		../../../Qt/5.7/gcc_64/include/QtGui/qopenglversionfunctions.h \
		../../../Qt/5.7/gcc_64/include/QtGui/QOpenGLFunctions_4_5_Core \
		../../../Qt/5.7/gcc_64/include/QtGui/qopenglfunctions_4_5_core.h \
		../../../Qt/5.7/gcc_64/include/QtGui/QOpenGLVersionFunctions \
		../../../Qt/5.7/gcc_64/include/QtCore/QTimer \
		../../../Qt/5.7/gcc_64/include/QtCore/qtimer.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qbasictimer.h \
		season.h \
		particle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pool.o pool.cpp

season.o: season.cpp season.h \
		particle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o season.o season.cpp

particle.o: particle.cpp particle.h \
		trianglewindow.h \
		camera.h \
		../../../Qt/5.7/gcc_64/include/QtGui/QOpenGLShaderProgram \
		../../../Qt/5.7/gcc_64/include/QtGui/qopenglshaderprogram.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qglobal.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qconfig.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qfeatures.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qsystemdetection.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qprocessordetection.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qtypeinfo.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qtypetraits.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qisenum.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qsysinfo.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qlogging.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qflags.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qatomic.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qbasicatomic.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qgenericatomic.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qglobalstatic.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qmutex.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qnumeric.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qversiontagging.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qopengl.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qt_windows.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qopengles2ext.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qopenglext.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qvector2d.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qpoint.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qnamespace.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qmetatype.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qbytearray.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qrefcount.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qarraydata.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qstring.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qchar.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qstringbuilder.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qvarlengtharray.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qcontainerfwd.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qalgorithms.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qobjectdefs.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qvector3d.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qvector4d.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qmatrix4x4.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qquaternion.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qgenericmatrix.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qdebug.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qhash.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qiterator.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qlist.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qhashfunctions.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qpair.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qbytearraylist.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qstringlist.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qregexp.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qstringmatcher.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qmap.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qtextstream.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qiodevice.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qobject.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qcoreevent.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qscopedpointer.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qobject_impl.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qlocale.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qvariant.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qshareddata.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qvector.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qset.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qcontiguouscache.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qsharedpointer.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qdatastream.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qrect.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qmargins.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qsize.h \
		../../../Qt/5.7/gcc_64/include/QtGui/QKeyEvent \
		../../../Qt/5.7/gcc_64/include/QtGui/qevent.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qwindowdefs.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qregion.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qkeysequence.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qurl.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qurlquery.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qfile.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qfiledevice.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qtouchdevice.h \
		openglwindow.h \
		../../../Qt/5.7/gcc_64/include/QtGui/QWindow \
		../../../Qt/5.7/gcc_64/include/QtGui/qwindow.h \
		../../../Qt/5.7/gcc_64/include/QtCore/QObject \
		../../../Qt/5.7/gcc_64/include/QtCore/QEvent \
		../../../Qt/5.7/gcc_64/include/QtCore/QMargins \
		../../../Qt/5.7/gcc_64/include/QtCore/QRect \
		../../../Qt/5.7/gcc_64/include/QtGui/qsurface.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qsurfaceformat.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qicon.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qpixmap.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qpaintdevice.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qcolor.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qrgb.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qrgba64.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qimage.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qpixelformat.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qtransform.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qmatrix.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qpolygon.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qline.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qpainterpath.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qcursor.h \
		../../../Qt/5.7/gcc_64/include/QtGui/QOpenGLFunctions \
		../../../Qt/5.7/gcc_64/include/QtGui/qopenglfunctions.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qopenglcontext.h \
		../../../Qt/5.7/gcc_64/include/QtCore/QScopedPointer \
		../../../Qt/5.7/gcc_64/include/QtGui/QSurfaceFormat \
		../../../Qt/5.7/gcc_64/include/QtGui/qopenglversionfunctions.h \
		../../../Qt/5.7/gcc_64/include/QtGui/QOpenGLFunctions_4_5_Core \
		../../../Qt/5.7/gcc_64/include/QtGui/qopenglfunctions_4_5_core.h \
		../../../Qt/5.7/gcc_64/include/QtGui/QOpenGLVersionFunctions \
		../../../Qt/5.7/gcc_64/include/QtCore/QTimer \
		../../../Qt/5.7/gcc_64/include/QtCore/qtimer.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qbasictimer.h \
		season.h \
		pool.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o particle.o particle.cpp

main.o: main.cpp trianglewindow.h \
		camera.h \
		../../../Qt/5.7/gcc_64/include/QtGui/QOpenGLShaderProgram \
		../../../Qt/5.7/gcc_64/include/QtGui/qopenglshaderprogram.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qglobal.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qconfig.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qfeatures.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qsystemdetection.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qprocessordetection.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qtypeinfo.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qtypetraits.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qisenum.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qsysinfo.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qlogging.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qflags.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qatomic.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qbasicatomic.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qgenericatomic.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qglobalstatic.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qmutex.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qnumeric.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qversiontagging.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qopengl.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qt_windows.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qopengles2ext.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qopenglext.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qvector2d.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qpoint.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qnamespace.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qmetatype.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qbytearray.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qrefcount.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qarraydata.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qstring.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qchar.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qstringbuilder.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qvarlengtharray.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qcontainerfwd.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qalgorithms.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qobjectdefs.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qvector3d.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qvector4d.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qmatrix4x4.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qquaternion.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qgenericmatrix.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qdebug.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qhash.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qiterator.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qlist.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qhashfunctions.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qpair.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qbytearraylist.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qstringlist.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qregexp.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qstringmatcher.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qmap.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qtextstream.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qiodevice.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qobject.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qcoreevent.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qscopedpointer.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qobject_impl.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qlocale.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qvariant.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qshareddata.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qvector.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qset.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qcontiguouscache.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qsharedpointer.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qdatastream.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qrect.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qmargins.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qsize.h \
		../../../Qt/5.7/gcc_64/include/QtGui/QKeyEvent \
		../../../Qt/5.7/gcc_64/include/QtGui/qevent.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qwindowdefs.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qregion.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qkeysequence.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qurl.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qurlquery.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qfile.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qfiledevice.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qtouchdevice.h \
		openglwindow.h \
		../../../Qt/5.7/gcc_64/include/QtGui/QWindow \
		../../../Qt/5.7/gcc_64/include/QtGui/qwindow.h \
		../../../Qt/5.7/gcc_64/include/QtCore/QObject \
		../../../Qt/5.7/gcc_64/include/QtCore/QEvent \
		../../../Qt/5.7/gcc_64/include/QtCore/QMargins \
		../../../Qt/5.7/gcc_64/include/QtCore/QRect \
		../../../Qt/5.7/gcc_64/include/QtGui/qsurface.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qsurfaceformat.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qicon.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qpixmap.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qpaintdevice.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qcolor.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qrgb.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qrgba64.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qimage.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qpixelformat.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qtransform.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qmatrix.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qpolygon.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qline.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qpainterpath.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qcursor.h \
		../../../Qt/5.7/gcc_64/include/QtGui/QOpenGLFunctions \
		../../../Qt/5.7/gcc_64/include/QtGui/qopenglfunctions.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qopenglcontext.h \
		../../../Qt/5.7/gcc_64/include/QtCore/QScopedPointer \
		../../../Qt/5.7/gcc_64/include/QtGui/QSurfaceFormat \
		../../../Qt/5.7/gcc_64/include/QtGui/qopenglversionfunctions.h \
		../../../Qt/5.7/gcc_64/include/QtGui/QOpenGLFunctions_4_5_Core \
		../../../Qt/5.7/gcc_64/include/QtGui/qopenglfunctions_4_5_core.h \
		../../../Qt/5.7/gcc_64/include/QtGui/QOpenGLVersionFunctions \
		../../../Qt/5.7/gcc_64/include/QtCore/QTimer \
		../../../Qt/5.7/gcc_64/include/QtCore/qtimer.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qbasictimer.h \
		season.h \
		particle.h \
		pool.h \
		../../../Qt/5.7/gcc_64/include/QtGui/QGuiApplication \
		../../../Qt/5.7/gcc_64/include/QtGui/qguiapplication.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qcoreapplication.h \
		../../../Qt/5.7/gcc_64/include/QtCore/qeventloop.h \
		../../../Qt/5.7/gcc_64/include/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

moc_openglwindow.o: moc_openglwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_openglwindow.o moc_openglwindow.cpp

moc_trianglewindow.o: moc_trianglewindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_trianglewindow.o moc_trianglewindow.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/home/resod/Qt/Examples/Qt-5.7/gui/openglwindow || mkdir -p $(INSTALL_ROOT)/home/resod/Qt/Examples/Qt-5.7/gui/openglwindow
	-$(INSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/home/resod/Qt/Examples/Qt-5.7/gui/openglwindow/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/home/resod/Qt/Examples/Qt-5.7/gui/openglwindow/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/home/resod/Qt/Examples/Qt-5.7/gui/openglwindow/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

